[package]
name = "apdu-dispatch"
version = "0.1.2"
authors = ["Conor Patrick <conor@solokeys.com>", "Nicolas Stalder <n@stalder.io>", "The Trussed developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "Dispatch layer after nfc-device and usbd-ccid"
repository = "https://github.com/trussed-dev/apdu-dispatch"
documentation = "https://docs.rs/apdu-dispatch"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delog = "0.1.4"
heapless = "0.7"
interchange = "0.3.0"
iso7816 = "0.1.1"

[dev-dependencies]
# Testing
serial_test = "0.6"
hex-literal = "0.3.4"

[features]
default = []
std = ["delog/std"]

log-all = []
log-none = []
log-debug = []
log-info = []
log-trace = []
log-warn = []
log-error = []

[patch.crates-io]
iso7816 = { git = "https://github.com/sosthene-nitrokey/iso7816.git", rev = "eee84fbb58f77d84f23c0fc793dac5ffe232aa5c" }
